logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.hibernate: OFF

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  datasource:
    username: test
    password: test
    url: "jdbc:postgresql://localhost:5432/test"
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
