logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.hibernate: OFF

ca:
  account:
    datastore:
#      type: jpa
      type: inmem

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: spring_jpa
    open-in-view: false
  datasource:
    username: test
    password: test
    url: "jdbc:postgresql://localhost:5432/test"
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
